bg/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import RedirectView
# from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url="blog/")),
]

blog/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    path('home/',views.home),
    path('about/',views.about),
    path('contact/',views.contact),
    path('dashboard/',views.dashboard),
    path('signup/',views.signup),
    path('user_login/',views.user_login),
    path('user_logout/',views.user_logout),
    
    path('update/<int:pk>/',views.update,name='update'),
    path('delete/<int:pk>/',views.delete,name='delete'),
    path('add/',views.add,name='add'),

    path('', RedirectView.as_view(url="home/")),
]

blog/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=100,unique=True)

    def __str__(self):
        return str(self.category_name)

class Post(models.Model):
    title = models.CharField(max_length=200)
    disc = models.TextField()
    category = models.ForeignKey(to = Category,on_delete=models.CASCADE,related_name="post_category")

blog/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm,\
    UsernameField
from django.contrib.auth.models import User
from django import forms
from django.utils.translation import gettext ,gettext_lazy as _
from blog.models import Post
from django.contrib.admin import widgets


class SignupForm(UserCreationForm):
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput(attrs = {'class':'form-control'}))
    password2 = forms.CharField(label='Comform Password',widget=forms.PasswordInput(attrs = {'class':'form-control'}))

    class Meta:
        model = User
        fields = ["username","first_name","last_name","email"]
        labels = {'email':"Email"}
        widgets = {'username':forms.TextInput(attrs = {'class':'form-control'}),
                   'first_name':forms.TextInput(attrs = {'class':'form-control'}),
                   'last_name':forms.TextInput(attrs = {'class':'form-control'}),
                   'email':forms.EmailInput(attrs = {'class':'form-control'}),
                   }
        
        
class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs = {'autofocus':True,'class':'form-control'}))
    password = forms.CharField(label = _("password") ,strip = False,widget=forms.PasswordInput(attrs = {'autocomplete':'current-password','class':'form-control'}))
    
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"
        labels = {'disc':"Description"}
        widgets = {'title':forms.TextInput(attrs = {'class':'form-control my-3'}),
                   'disc':forms.Textarea(attrs = {'class':'form-control my-3'}),}

blog/views.py
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from blog.forms import SignupForm
from blog.forms import LoginForm,PostForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from blog.models import Post
from django.contrib.auth.models import Group, User

# Create your views here.
def home(req):
    post = Post.objects.all()
    return render(req,"home.html",context = {"post":post})

def about(req):
    return render(req,"about.html")

def contact(req):
    return render(req,"contact.html")

def dashboard(req):
    if req.user.is_authenticated:
        post = Post.objects.all()
        
        user = req.user
        full_name = user.get_full_name()
        
        gps = user.groups.all()
        return render(req,"dashboard.html",{"post":post,"fnm":full_name,"gps":gps})
    else:
        return HttpResponseRedirect("/blog/user_login")
def signup(req):
    if req.method == "POST":
        form = SignupForm(req.POST)
        if form.is_valid():
            user = form.save()
            
            group = Group.objects.get(name='Auther')
            user.groups.add(group)
            
            messages.success(req,"Successfully Register!!!!")
            messages.warning(req,"Please login!!!")
            return HttpResponseRedirect("/blog/user_login")
    else:
        form = SignupForm()       
    
    return render(req,"signup.html",{"fm":form})

def user_login(req):
    if not req.user.is_authenticated:
        if req.method == "POST":
            form = LoginForm(request=req,data=req.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                up= form.cleaned_data['password']
                user = authenticate(username=uname,password=up)
                if user is not None:
                    login(req,user)
                    messages.success(req,"Login successfully!!!")
                    return HttpResponseRedirect("/blog/dashboard")
                    # return render(req,"dashboard.html")
        else:
            form = LoginForm()
        
        return render(req,"login.html",{"fm":form})
    else:
        return HttpResponseRedirect("/blog/dashboard")
def user_logout(req):
    logout(req)
    messages.success(req,"Logout successfully")
    return HttpResponseRedirect("/blog/home")
    # return render(req,"home.html")
    
def delete(req,pk):
    if req.user.is_authenticated:
        if req.method == "POST":
            pi = Post.objects.get(pk=pk)
            pi.delete()
            return HttpResponseRedirect("/blog/dashboard")
    else:
        return HttpResponseRedirect("/blog/user_login")

def update(req,pk):
    if req.user.is_authenticated:
        if req.method == "POST":
            pi = Post.objects.get(pk=pk)
            fm = PostForm(req.POST,instance=pi)
            if fm.is_valid():
                fm.save()
                messages.success(req,"Successfully Updated!!!!")
                return HttpResponseRedirect("/blog/dashboard")
        else:
            pi = Post.objects.get(pk=pk)
            fm = PostForm(instance=pi)       
        return render(req,"update.html",{"fm":fm})
    else:
        return HttpResponseRedirect("/blog/user_login")

def add(req):
    if req.user.is_authenticated:
        if req.method=="POST":
            fm = PostForm(req.POST)
            if fm.is_valid():
                fm.save()
                messages.success(req,"Successfilly Added post!!!!")
                return HttpResponseRedirect("/blog/dashboard")
        else:
            fm = PostForm()
        return render(req,"add.html",{"fm":fm})
    else:
        return HttpResponseRedirect("/blog/user_login")
    

blog/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-10 my-5 pl-5">
    <h3 class="text-black my-5">About Page</h3>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quas culpa dicta fuga ullam quis quia est cupiditate molestias, vero sapiente distinctio reiciendis explicabo doloremque, nesciunt doloribus, nostrum laborum dignissimos? Qui.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, itaque aliquam nemo quidem expedita eos numquam voluptates earum neque qui ipsam dolore dolores iusto obcaecati consequuntur odit asperiores rem fuga.</p>
</div>
{% endblock %}

blog/templates/add.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8 offset-2">
        <h1 class="alert alert-success my-3 text-center">Add Post</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{fm.as_p}}
            <input type="submit" value="Add" class="btn btn-success border">
            <a href="/blog/dashboard" class="btn btn-danger border">Cancel</a>
        </form>
        
    </div>
</div>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/css/font-awesome.min.css">

    <title>Base</title>
</head>
<body>

<div class="container-fluid bg-dark">
    {% include 'navbar.html' %}
</div>
<div class="container">
<div class="row">
    <div class="col-md-12">
        {% block msg %}
        {% endblock %}
    </div>
</div>

<div class="row">
   
        {% block side %}
        {% endblock %}

        {% block content %}
        {% endblock %}
  

</div>

<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>   
</body>
</html>

blog/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-10 my-5 pl-5">
    <h3 class="text-black my-5">Contact Page</h3>
    <form method="get" action="">
        <label for="mobile">Mobile No. ::</label>
        <input type="text" placeholder="Enter Mobile no. or Email"><br><br>
        <div class="form-group">
            <label for="my-textarea">Text ::</label>
            <textarea id="my-textarea" class="form-control" name="" rows="3"></textarea>
        </div><br><br>
        <button class="btn btn-success">Submit</button>
    </form>
    </div>
{% endblock %}

blog/templates/dashboard.html
{% extends 'base.html' %}


{% block msg %}
{% if messages %}
    {% for ms in messages %}
        <div class="alert alert-{{ms.tags}} m-3">{{ms}}</div>
    {% endfor %}
{% endif %}
{% endblock %}

{% block side %}
<div class="col-md-2 my-5 text-center">
    <h4 class="my-5">My Profile</h4>
    <h5>{{full_name}}</h5>
{% for gp in gps %}
    <p>{{gp.name}}</p>
{% endfor %}
</div>

{% endblock %}

{% block content %}
    
<div class="col-md-10">
    <a href="/blog/add" class="btn btn-success my-4 border">Add Post</a>
    <h1 class="text-center alert alert-dark p-2 ">Dash Board</h1>
   
    {% if post %}
    <table class="table table-hover table1">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col" class="pl-3">Title</th>
            <th scope="col" class="pl-5">Description</th>
            <th scope="col" class="pl-2">Action</th>
          </tr>
        </thead>
        {% for post in post %}
        <tbody>
           
          <tr>
            <th scope="row">{{post.id}}</th>
            <td>{{post.title}}</td>
            <td><div class="td_td">{{post.disc}}</div></td>
            <td>
                <a href="{% url 'update' post.id %}" class="btn btn-warning m-2 border">Edit</a>
                {% if perms.blog.delete_post %}
                <form action="{% url 'delete' post.id %}" method='POST' class="d-inline"> 
                    {% csrf_token %}
                    <button class="btn btn-danger border">Delete</button>
                    <!-- <input type="submit" class="btn btn-danger btn-sm" value="Delete"> -->
                </form>
                {% endif %}
    
            </td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
      {% endif %}
</div>

{% endblock %} 

blog/templates/home.html
{% extends 'base.html' %}

{% block msg %}
{% if messages %}
{% for ms in messages %}
<div class="alert alert-{{ms.tags}} m-3">{{ms}}</div>
{% endfor %}
{% endif %}
{% endblock %}

{% block content %}
<div class="col-md-10 my-5 pl-5">
    <h3 class="text-black">Home Page</h3>
        {% for post in post %}
    <div class="jumbotron jumbotron-fluid jumbo-color m-5">
        <div class="container p-3 border">
           <h1 class="display-7 m-4">{{post.title}}</h1>
           <p class="lead m-4">{{post.disc}}</p>
        </div>
    </div>    
        {% endfor %}
    
</div>

{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}

{% block msg %}
{% if messages %}
{% for ms in messages %}
<div class="alert alert-{{ms.tags}} m-3">{{ms}}</div>
{% endfor %}
{% endif %}
{% endblock %}

{% block content %}
    <div class="col-md-6 offset-3 ">
        <h3 class="text-black my-5 ">Login Page</h3>
        <form action="" method="POST">
        {% csrf_token %}
            {{fm.as_p}}
            <br>
            <input type="submit" value="Submit" class="btn btn-primary border">
        </form>
        </div>
    </div>
{% endblock %}

blog/templates/logout.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-10 my-5 pl-5">
    <h3 class="text-black my-5">Logout Page</h3>
    </div>
{% endblock %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand mr-5" href="#">BlogPost</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/blog/about">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/blog/contact">Contact</a>
            </li>


            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="/blog/dashboard">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/blog/user_logout">Logout</a>
            </li>
           
            {% else %}

            <li class="nav-item">
                <a class="nav-link" href="/blog/signup">Signup</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/blog/user_login">Login</a>
            </li>
            {% endif %}


        </ul>
    </div>
</nav>

blog/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-3">
    <h3 class="text-black my-5">Signup Page</h3>
    <form action="" method="POST">
    {% csrf_token %}
        {{fm.as_p}}
        <br>
        <input type="submit" value="Submit" class="btn btn-primary border">
    </form>
    </div>
{% endblock %}

blog/templates/update.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8 offset-2">
        <h1 class="alert alert-success p-2 my-3 text-center">Update Post</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{fm.as_p}}
            <input type="submit" value="Update" class="btn btn-success">
            <a href="/blog/dashboard" class="btn btn-danger">Cancel</a>
        </form>
        
    </div>
</div>
{% endblock %}